# Extracted Theme Conf
$base = rgb(080707)
$blue = rgb(4e4e4e)
$rosewater = rgb(f5e0dc)
$pink = rgb(f5c2e7)
$red = rgb(f38ba8)
$peach = rgb(fab387)
$yellow = rgb(f9e2af)
$green = rgb(a6e3a1)
$lavender = rgb(b4befe)
$text = rgb(cdd6f4)
$crust = rgb(11111b)

$base_bg = rgba(080707a6)
$surface_pill = rgb(4e4e4e)
$primary_blue = rgb(4e4e4e)
$middle_bg = rgb(080707)
