# Extracted Theme Conf
$base = rgb(09bdfd)
$blue = rgb(023518)
$rosewater = rgb(f5e0dc)
$pink = rgb(f5c2e7)
$red = rgb(f38ba8)
$peach = rgb(fab387)
$yellow = rgb(f9e2af)
$green = rgb(a6e3a1)
$lavender = rgb(b4befe)
$text = rgb(11111b)
$crust = rgb(11111b)

$base_bg = rgba(09bdfda6)
$surface_pill = rgb(023518)
$primary_blue = rgb(023518)
$middle_bg = rgb(09bdfd)
